// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-leads.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function unauthorized() {
  return {
    content: [{ type: "text", text: "Not authenticated" }],
    isError: true
  };
}

// src/lib/mcp/tools/list-leads.ts
var list_leads_default = defineTool({
  name: "list_leads",
  title: "List leads",
  description: "List qualified leads captured by the Nexus AI consultant, most recent first. Admin-only.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Maximum number of leads to return (1-100, default 20)."),
    status: z.string().optional().describe("Optional status filter, e.g. 'new', 'contacted', 'qualified'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    const sb = supabaseForUser(ctx);
    let q = sb.from("leads").select("id, session_id, name, email, company, intent_category, budget_range, timeline, status, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { leads: data }
    };
  }
});

// src/lib/mcp/tools/get-lead.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_lead_default = defineTool2({
  name: "get_lead",
  title: "Get lead with transcript",
  description: "Fetch a single lead with its full chat transcript from the Nexus AI consultant. Admin-only.",
  inputSchema: {
    lead_id: z2.string().uuid().describe("The lead's UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lead_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    const sb = supabaseForUser(ctx);
    const { data: lead, error: leadErr } = await sb.from("leads").select("*").eq("id", lead_id).maybeSingle();
    if (leadErr) return { content: [{ type: "text", text: leadErr.message }], isError: true };
    if (!lead) return { content: [{ type: "text", text: "Lead not found" }], isError: true };
    const { data: messages, error: msgErr } = await sb.from("chat_messages").select("role, content, created_at").eq("session_id", lead.session_id).order("created_at", { ascending: true });
    if (msgErr) return { content: [{ type: "text", text: msgErr.message }], isError: true };
    const payload = { lead, messages: messages ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-recent-analytics.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_recent_analytics_default = defineTool3({
  name: "list_recent_analytics",
  title: "List recent chat analytics",
  description: "List recent chat analytics events (e.g. module_preloaded) from the consultant. Admin-only.",
  inputSchema: {
    limit: z3.number().int().min(1).max(200).optional().describe("Max events (default 50)."),
    event_type: z3.string().optional().describe("Optional event_type filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, event_type }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    const sb = supabaseForUser(ctx);
    let q = sb.from("chat_analytics").select("id, session_id, event_type, module_type, metadata, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (event_type) q = q.eq("event_type", event_type);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { events: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qzadmutiloogikxagvus";
var mcp_default = defineMcp({
  name: "nexus-ai-mcp",
  title: "Nexus AI MCP",
  version: "0.1.0",
  instructions: "Tools for the Nexus AI consultant app. Admins can list qualified leads, fetch a lead's chat transcript, and review recent chat analytics events. All access is scoped to the signed-in admin user via RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_leads_default, get_lead_default, list_recent_analytics_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
